server:
  port: 9090
  servlet:
    context-path: /SBFormApp
    

spring:
  mvc:
    view:
      prefix: /views/ 
      suffix: .jsp
  mail:
    host: smtp.gmail.com
    port: 587
    username: asifraza4101995@gmail.com
    password: 
    properties:
      mail:
       smtp:
        auth: true
        starttls:
         enable: true
   
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mydb
    username: root
    password: root
 
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      dialect: org.hibernate.dialect.MySQL55Dialect
    
      
paypal:
  mode: sandbox
  client:
   id: AYSq3RDGsmBLJE-otTkBtM-jBRd1TCQwFf9RGfwddNXWz0uFU9ztymylOhRS
   secret: EGnHDxD_qRPdaLdZz8iCr8N7_MzF-YHPTkjs6NKYQvQSBngp4PTTVWkPZRbL      


management:
  endpoints:
    web:
      exposure:
        include: "*"
        
  endpoint:
    env:
      enabled: true
    info:
      enabled: true
    beans:
      enabled: true
    health:
      enabled: true
    metrics:
      enabled: true
    threaddump:
      enabled: true
    heapdump:
      enabled: true
    configprops:
      enabled: true
      


##email configuration
#spring.mail.host=smtp.gmail.com
#spring.mail.port=587
#spring.mail.username=sathya123siva@gmail.com
#spring.mail.password=siva123@
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true


#paypal configuration key
#paypal.mode=sandbox
#paypal.client.id=AYSq3RDGsmBLJE-otTkBtM-jBRd1TCQwFf9RGfwddNXWz0uFU9ztymylOhRS
#paypal.client.secret=EGnHDxD_qRPdaLdZz8iCr8N7_MzF-YHPTkjs6NKYQvQSBngp4PTTVWkPZRbL
    
